In [3]:
import os
import math 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
#ignore warning messages to ensure clean outputs
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('NBA_Contract_Data_csv.csv')
df.head()

Season  Age   Tm  Player Pos   G  GS    MP   FG   FGA  ...  ORB  DRB  TRB  \
0  2015-16   19  PHO  Booker  SG  76  51  27.7  4.8  11.4  ...  0.4  2.1  2.5   
1  2016-17   20  PHO  Booker  SG  78  78  35.0  7.8  18.3  ...  0.6  2.6  3.2   
2  2017-18   21  PHO  Booker  SG  54  54  34.5  8.4  19.5  ...  0.5  4.0  4.5   
3  2018-19   22  PHO  Booker  SG  64  64  35.0  9.2  19.6  ...  0.6  3.5  4.1   
4  2019-20   23  PHO  Booker  SG  70  70  35.9  9.0  18.3  ...  0.4  3.8  4.2   

   AST  STL  BLK  TOV   PF   PTS  Max  
0  2.6  0.6  0.3  2.1  3.0  13.8   No  
1  3.4  0.9  0.3  3.1  3.1  22.1   No  
2  4.7  0.9  0.3  3.6  3.1  24.9   No  
3  6.8  0.9  0.2  4.1  3.1  26.6   No  
4  6.5  0.7  0.3  3.8  3.0  26.6   No  

[5 rows x 31 columns]

In [5]:
df.columns

Index(['Season', 'Age', 'Tm', 'Player', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'Max'],
      dtype='object')

In [6]:
dfo=df.select_dtypes(include=['object']) # select object type columns
df = pd.concat([df.drop(dfo, axis=1), pd.get_dummies(dfo)], axis=1)

In [7]:
df.head()

Age   G  GS    MP   FG   FGA    FG%   3P  3PA    3P%  ...  Player_Oladipo  \
0   19  76  51  27.7  4.8  11.4  0.423  1.3  3.8  0.343  ...               0   
1   20  78  78  35.0  7.8  18.3  0.423  1.9  5.2  0.363  ...               0   
2   21  54  54  34.5  8.4  19.5  0.432  2.7  7.1  0.383  ...               0   
3   22  64  64  35.0  9.2  19.6  0.467  2.1  6.5  0.326  ...               0   
4   23  70  70  35.9  9.0  18.3  0.489  2.0  5.7  0.354  ...               0   

   Player_Schroder  Player_Thompson  Player_Westbrook  Pos_PG  Pos_PG,SG  \
0                0                0                 0       0          0   
1                0                0                 0       0          0   
2                0                0                 0       0          0   
3                0                0                 0       0          0   
4                0                0                 0       0          0   

   Pos_SF  Pos_SG  Max_No  Max_Yes  
0       0       1       1        0  
1       0       1       1        0  
2       0       1       1        0  
3       0       1       1        0  
4       0       1       1        0  

[5 rows x 79 columns]

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X= df.drop(['PTS'],axis=1)
y=df['PTS']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=1)
X_train = pd.get_dummies(X_train)
X_test = pd.get_dummies(X_test)

In [11]:
#Import ML models:

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.model_selection import validation_curve

# Splitting the dataset into training and test set:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Feature Scaling:



In [12]:
scaler_x = MinMaxScaler((-1,1))
X_train = scaler_x.fit_transform(X_train)
X_test = scaler_x.transform(X_test)

In [13]:
from sklearn import linear_model

In [14]:
reg=linear_model.LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [15]:
reg.intercept_

20.88925534977957

In [16]:
reg.predict(X_test)

array([25.39062807, 24.61068308, 25.72042516, 16.8281431 , 19.97976075,
       22.92186535, 14.6352831 , 14.59764033, 10.86803058, 20.03714806,
       23.0928499 , 21.63518094,  9.43879599, 26.69347389, 14.4705263 ,
       15.95429586, 29.12255203, 10.00592237, 14.40749352, 15.56059173,
       31.800871  , 22.87477077, 16.93830656, 23.97160631, 14.01919766,
       21.10120255, 17.17062748, 14.04022038, 16.15395994, 13.76000691,
       23.89035566, 24.6695146 , 17.87110817, 22.13197027, 13.74560917,
       15.58526727, 10.99723255, 26.52210735, 16.5640979 ])

In [17]:
reg.score(X_test,y_test)

0.9995954467039481

In [18]:
cv_scores_test= cross_val_score(reg,X_test,y_test,cv=5,scoring='roc_auc')
cv_scores_train= cross_val_score(reg,X_train,y_train,cv=5,scoring='roc_auc')
print(cv_scores_test)
cv_scores_lr_test= cv_scores_test.mean()
cv_scores_lr_train= cv_scores_train.mean()
cv_scores_std_test_lr= cv_scores_test.std()
print ('Mean cross validation test score: ' +str(cv_scores_lr_test))
print ('Mean cross validation train score: ' +str(cv_scores_lr_train))
print ('Standard deviation in cv test scores: ' +str(cv_scores_std_test_lr))

[nan nan nan nan nan]
Mean cross validation test score: nan
Mean cross validation train score: nan
Standard deviation in cv test scores: nan


In [19]:
#This score seems too accurate and may overfit. 
#It also doesn't help determain who gets a max contract, but can be useful in finding how to imporve stats. 

In [20]:
#ClassifierSetUp

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
df1 = pd.read_csv('NBA_Contract_Data_csv.csv')
df1

Season  Age   Tm  Player Pos   G  GS    MP   FG   FGA  ...  ORB  DRB  \
0    2015-16   19  PHO  Booker  SG  76  51  27.7  4.8  11.4  ...  0.4  2.1   
1    2016-17   20  PHO  Booker  SG  78  78  35.0  7.8  18.3  ...  0.6  2.6   
2    2017-18   21  PHO  Booker  SG  54  54  34.5  8.4  19.5  ...  0.5  4.0   
3    2018-19   22  PHO  Booker  SG  64  64  35.0  9.2  19.6  ...  0.6  3.5   
4    2019-20   23  PHO  Booker  SG  70  70  35.9  9.0  18.3  ...  0.4  3.8   
..       ...  ...  ...     ...  ..  ..  ..   ...  ...   ...  ...  ...  ...   
123  2017-18   29  HOU  Gordon  SG  69  30  31.2  6.0  14.1  ...  0.4  2.1   
124  2018-19   30  HOU  Gordon  SG  68  53  31.7  5.6  13.8  ...  0.3  1.9   
125  2019-20   31  HOU  Gordon  SF  36  15  28.2  4.8  12.9  ...  0.3  1.7   
126  2020-21   32  HOU  Gordon  SG  27  13  29.2  5.9  13.6  ...  0.3  1.9   
127  2021-22   33  HOU  Gordon  SG  57  46  29.3  4.7   9.9  ...  0.3  1.7   

     TRB  AST  STL  BLK  TOV   PF   PTS  Max  
0    2.5  2.6  0.6  0.3  2.1  3.0  13.8   No  
1    3.2  3.4  0.9  0.3  3.1  3.1  22.1   No  
2    4.5  4.7  0.9  0.3  3.6  3.1  24.9   No  
3    4.1  6.8  0.9  0.2  4.1  3.1  26.6   No  
4    4.2  6.5  0.7  0.3  3.8  3.0  26.6   No  
..   ...  ...  ...  ...  ...  ...   ...  ...  
123  2.5  2.2  0.6  0.4  1.9  1.7  18.0   No  
124  2.2  1.9  0.6  0.4  1.3  2.1  16.2   No  
125  2.0  1.5  0.6  0.4  1.2  1.9  14.4   No  
126  2.1  2.6  0.5  0.5  1.9  1.6  17.8   No  
127  2.0  2.7  0.5  0.3  1.9  1.1  13.4   No  

[128 rows x 31 columns]

In [23]:
df1.columns

Index(['Season', 'Age', 'Tm', 'Player', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'Max'],
      dtype='object')

In [24]:
dfo1=df1.select_dtypes(include=['object'])

In [25]:
dfo1

Season   Tm  Player Pos Max
0    2015-16  PHO  Booker  SG  No
1    2016-17  PHO  Booker  SG  No
2    2017-18  PHO  Booker  SG  No
3    2018-19  PHO  Booker  SG  No
4    2019-20  PHO  Booker  SG  No
..       ...  ...     ...  ..  ..
123  2017-18  HOU  Gordon  SG  No
124  2018-19  HOU  Gordon  SG  No
125  2019-20  HOU  Gordon  SF  No
126  2020-21  HOU  Gordon  SG  No
127  2021-22  HOU  Gordon  SG  No

[128 rows x 5 columns]

In [26]:
X1= df1.drop(['Max'],axis=1)
y1=df1['Max']

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size=.35, random_state=1)
X_train = pd.get_dummies(X_train)
X_test = pd.get_dummies(X_test)

In [28]:
#RandomForest

In [29]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(bootstrap=True,n_estimators=100,criterion='entropy')
rfc.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy')

In [30]:
y_pred_rf=rfc.predict(X_test)
y_pred_rf

array(['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes',
       'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No',
       'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes',
       'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes',
       'Yes', 'Yes', 'No', 'Yes', 'Yes'], dtype=object)

In [31]:
rfc.score(X_test,y_test)

0.9111111111111111

In [300]:
rfc_matrix=confusion_matrix(y_test,y_pred_rf)
rfc_matrix

array([[22,  1],
       [ 2, 20]], dtype=int64)

In [261]:
#The accuracy is high, but seems more plausible than regression.
#Much like in the NBA, many players eligible for the SuperMax contract are usually offered the contract.

In [33]:
#DecisionTree

In [34]:
from sklearn.tree import DecisionTreeClassifier

In [35]:
dtc=DecisionTreeClassifier(random_state=1)

In [36]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier(random_state=1)

In [37]:
y_pred_dtf=dtc.predict(X_test)
y_pred_dtf

array(['No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes',
       'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No',
       'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No',
       'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No',
       'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes'], dtype=object)

In [38]:
dtc.score(X_test,y_test)

0.6888888888888889

In [39]:
dtc_matrix=confusion_matrix(y_test,y_pred_dtf)
dtc_matrix

array([[12, 11],
       [ 3, 19]], dtype=int64)

In [ ]:
#The results are less accurate compared to random forest because it is restricted by the use of only one decision tree.

In [40]:
#GradientBoosting

In [41]:
from sklearn.ensemble import ExtraTreesClassifier, GradientBoostingClassifier
gbc = GradientBoostingClassifier(subsample=0.7, learning_rate=0.06 , n_estimators=160, random_state=6, max_depth=8, max_leaf_nodes=100)
gbc.fit(X_train, y_train)

GradientBoostingClassifier(learning_rate=0.06, max_depth=8, max_leaf_nodes=100,
                           n_estimators=160, random_state=6, subsample=0.7)

In [42]:
y_pred_gbc=gbc.predict(X_test)
y_pred_gbc

array(['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes',
       'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No',
       'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes',
       'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes',
       'Yes', 'Yes', 'No', 'Yes', 'Yes'], dtype=object)

In [43]:
gbc.score(X_test,y_test)

0.8444444444444444

In [44]:
gbc_matrix=confusion_matrix(y_test,y_pred_gbc)
gbc_matrix

array([[19,  4],
       [ 3, 19]], dtype=int64)

In [ ]:
#This method was very sensitive when it came to adjusting the hyperparmeters 
#Each parameter had a sweet spot to help its acurracy, the score went from around 0.66 all the way to a score of 0.84